version: '3.4'

services:
  pharmaflow.administrationservice:
    image: ${DOCKER_REGISTRY-}pharmaflowadministrationservice
    ports:
      - 55443:443
      - 15020:8080
    build:
      context: .
      dockerfile: PharmaFlow.AdministrationService/Dockerfile

